### ISSUE TITLE
How can i use your project or build the Adium Xtra

### ISSUE THREAD

**Issue by mistergraphx** [tripplet/adium-mattermost#1]
Hi,

I search a solution to use Mattermost in Adium, mostly because of the exessive RAM use of the mattermost app build with electron.

Does your addon project was functionnal ?
 i d'ont know actually how to build it and test, that's the main reason of my question.

Thanks for your answer.
Best regards

**Comment by tripplet** [comment]
This only a basic start project which I never finished.
I will not work out of the box without a lot of programming work.
